version: '3'

volumes: 
  node_modules:

services:
  frontend:
    image: node:alpine
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '5000:5000'
    command: sh -c "cd app; yarn; yarn run dev"
